name: Build project

on:
  workflow_dispatch:
    inputs:
      targetPlatform:
        description: 'Platform to build'
        required: true
        type: choice
        options:
         # - StandaloneOSX
         # - StandaloneWindows
         # - StandaloneWindows64
         # - StandaloneLinux64
         # - iOS
          - WebGL
          - Android

jobs:
  build:
    name: Build for ${{ inputs.targetPlatform }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ inputs.targetPlatform }}
          restore-keys: Library-

      # Проверяем свободное место ДО очистки
      - name: Check disk space before cleanup
        run: df -h

      # Освобождаем место на runner
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      # Проверяем свободное место ПОСЛЕ очистки
      - name: Check disk space after cleanup
        run: df -h

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ inputs.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ inputs.targetPlatform }}
          path: build/${{ inputs.targetPlatform }}
